format = """
$os\
[î‚¶](fg:#769ff0)\
$username\
$hostname\
$directory\
[î‚´](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[î‚´](fg:#394260 bg:#212736)\
$nodejs\
$rust\
$golang\
$java\
$python\
$terraform\
$nix_shell\
$helm\
[î‚´](fg:#212736 bg:#1d2230)\
$kubernetes\
$azure\
$aws\
$container\
[î‚´ ](fg:#1d2230)\
$cmd_duration\
\n$character"""

[character]
success_symbol = '[â¯](#769ff0)'
error_symbol = '[â¯](#769ff0)'

[os]
#style = "fg:#e3e5e5 bg:#769ff0"
format = "$symbol($style)"
disabled = true

[username]
show_always = false
style_user = "fg:#e3e5e5 bg:#769ff0"
format = "[$user@]($style)"
disabled = true

[hostname]
ssh_only = true
style = "fg:#e3e5e5 bg:#769ff0"
format = "[$hostname]($style)"
disabled = true

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[$path]($style)"
truncation_length = 15
truncate_to_repo = false
#truncation_symbol = "â€¦/"

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "

[git_branch]
symbol = "ï˜"
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[$ahead_behind ($all_status)](fg:#769ff0 bg:#394260)]($style)'
modified = 'ğŸ“'
conflicted = 'ğŸ”¥'
staged = 'ğŸ’¾'
up_to_date = 'âœ“'
ahead = 'îª¡'
behind = 'îªš'
untracked = 'ó°¼…'
stashed = 'ğŸ“¦'
diverged = 'ó°¦»'
deleted = 'îª'

[cmd_duration]
min_time = 1_000
#style = "bg:#1d2230"
format = 'ïº $duration'

# Languages
[nodejs]
symbol = 'î´'
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[terraform]
symbol = 'î¢½'
style = "bg:#212736"
format = '[[ $symbol ($workspace) ](fg:#769ff0 bg:#212736)]($style)'
detect_extensions = 	['tf', 'tfplan', 'tfstate', "hcl"]

#[ansible]
##symbol = 'îœ£'
#style = "bg:#212736"
#format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = 'î™'
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[java]
symbol = 'îœ¸'
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[python]
symbol = 'îœ¼'
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[helm]
symbol = 'îŸ»'
style = "bg:#1d2230"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[nix_shell]
symbol = 'îŸ»'
style = "bg:#1d2230"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

# Other
[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[ ïº $time ](fg:#a0a9cb bg:#1d2230)]($style)'

[aws]
disabled = false
symbol ='ïƒ¯  '
style = "bg:#1d2230"
format = '[[ $symbol$aws($profile)](fg:#a0a9cb bg:#1d2230)]($style)'

[azure]
disabled = false
style = "bg:#1d2230"
format = '[[ $symbol$azure($subscription)](fg:#a0a9cb bg:#1d2230)]($style)'

[kubernetes]
disabled = false
symbol = 'î '
style = "bg:#1d2230"
format = '[[ $symbol$kubernetes $context](fg:#a0a9cb bg:#1d2230)]($style)'

[container]
style = "bg:#1d2230"
format = '[[ $symbol$name ](fg:#a0a9cb bg:#1d2230)]($style)'
